create_clock -period 10.000 -name clk_100 -waveform {0.000 5.000} [get_ports Clk]

set_property IOSTANDARD LVCMOS33 [get_ports Clk]
set_property IOSTANDARD LVCMOS25 [get_ports reset_rtl_0]
set_property PACKAGE_PIN N15 [get_ports Clk]
set_property PACKAGE_PIN J2 [get_ports reset_rtl_0]

#HDMI

set_property -dict { PACKAGE_PIN V17   IOSTANDARD TMDS_33 } [get_ports {hdmi_tmds_clk_n}]
set_property -dict { PACKAGE_PIN U16   IOSTANDARD TMDS_33 } [get_ports {hdmi_tmds_clk_p}]

set_property -dict { PACKAGE_PIN U18   IOSTANDARD TMDS_33  } [get_ports {hdmi_tmds_data_n[0]}]
set_property -dict { PACKAGE_PIN R17   IOSTANDARD TMDS_33  } [get_ports {hdmi_tmds_data_n[1]}]
set_property -dict { PACKAGE_PIN T14   IOSTANDARD TMDS_33  } [get_ports {hdmi_tmds_data_n[2]}]
                                    
set_property -dict { PACKAGE_PIN U17   IOSTANDARD TMDS_33  } [get_ports {hdmi_tmds_data_p[0]}]
set_property -dict { PACKAGE_PIN R16   IOSTANDARD TMDS_33  } [get_ports {hdmi_tmds_data_p[1]}]
set_property -dict { PACKAGE_PIN R14   IOSTANDARD TMDS_33  } [get_ports {hdmi_tmds_data_p[2]}]


#NDS Pins
set_property PACKAGE_PIN J16 [get_ports T_R0]
set_property IOSTANDARD LVCMOS33 [get_ports T_R0]
set_property PACKAGE_PIN J15 [get_ports T_R1]
set_property IOSTANDARD LVCMOS33 [get_ports T_R1]
set_property PACKAGE_PIN K16 [get_ports T_R2]
set_property IOSTANDARD LVCMOS33 [get_ports T_R2]
set_property PACKAGE_PIN K14 [get_ports T_R3]
set_property IOSTANDARD LVCMOS33 [get_ports T_R3]
set_property PACKAGE_PIN H17 [get_ports T_R4]
set_property IOSTANDARD LVCMOS33 [get_ports T_R4]
set_property PACKAGE_PIN G18 [get_ports T_R5]
set_property IOSTANDARD LVCMOS33 [get_ports T_R5]

set_property PACKAGE_PIN H16 [get_ports T_G0]
set_property IOSTANDARD LVCMOS33 [get_ports T_G0]
set_property PACKAGE_PIN H18 [get_ports T_G1]
set_property IOSTANDARD LVCMOS33 [get_ports T_G1]
set_property PACKAGE_PIN G16 [get_ports T_G2]
set_property IOSTANDARD LVCMOS33 [get_ports T_G2]
set_property PACKAGE_PIN E16 [get_ports T_G3]
set_property IOSTANDARD LVCMOS33 [get_ports T_G3]
set_property PACKAGE_PIN C11 [get_ports T_G4]
set_property IOSTANDARD LVCMOS33 [get_ports T_G4]
set_property PACKAGE_PIN C12 [get_ports T_G5]
set_property IOSTANDARD LVCMOS33 [get_ports T_G5]

set_property PACKAGE_PIN D10 [get_ports T_B0]
set_property IOSTANDARD LVCMOS33 [get_ports T_B0]
set_property PACKAGE_PIN D11 [get_ports T_B1]
set_property IOSTANDARD LVCMOS33 [get_ports T_B1]
set_property PACKAGE_PIN E15 [get_ports T_B2]
set_property IOSTANDARD LVCMOS33 [get_ports T_B2]
set_property PACKAGE_PIN H14 [get_ports T_B3]
set_property IOSTANDARD LVCMOS33 [get_ports T_B3]
set_property PACKAGE_PIN E14 [get_ports T_B4]
set_property IOSTANDARD LVCMOS33 [get_ports T_B4]
set_property PACKAGE_PIN H13 [get_ports T_B5]
set_property IOSTANDARD LVCMOS33 [get_ports T_B5]

set_property PACKAGE_PIN J14 [get_ports DCLK]
set_property IOSTANDARD LVCMOS33 [get_ports DCLK]
create_clock -period 339.510 -name dclk -waveform {0.000 169.755} [get_ports DCLK]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets DCLK_IBUF]
set_property PACKAGE_PIN F15 [get_ports GSP]
set_property IOSTANDARD LVCMOS33 [get_ports GSP]
set_property PACKAGE_PIN J13 [get_ports LS]
set_property IOSTANDARD LVCMOS33 [get_ports LS]

#LED0
set_property IOSTANDARD LVCMOS33 [get_ports LED0]
set_property PACKAGE_PIN C13 [get_ports LED0]
set_property IOSTANDARD LVCMOS33 [get_ports LED1]
set_property PACKAGE_PIN C14 [get_ports LED1]
set_property IOSTANDARD LVCMOS33 [get_ports LED2]
set_property PACKAGE_PIN D14 [get_ports LED2]
set_property IOSTANDARD LVCMOS33 [get_ports LED3]
set_property PACKAGE_PIN D15 [get_ports LED3]

set_property PULLDOWN true [get_ports LED0]
set_property PULLDOWN true [get_ports LED1]
set_property PULLDOWN true [get_ports LED2]
set_property PULLDOWN true [get_ports LED3]