#clk
create_clock -period 10.000 -name clk_100 -waveform {0.000 5.000} [get_ports Clk]

#uart and reset
set_property IOSTANDARD LVCMOS33 [get_ports Clk]
set_property IOSTANDARD LVCMOS25 [get_ports reset_rtl_0]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_txd]
set_property PACKAGE_PIN N15 [get_ports Clk]
set_property PACKAGE_PIN J2 [get_ports reset_rtl_0]
set_property PACKAGE_PIN B16 [get_ports uart_rtl_0_rxd]
set_property PACKAGE_PIN A16 [get_ports uart_rtl_0_txd]

#usb pins
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_usb_int_tri_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports usb_spi_miso]
set_property IOSTANDARD LVCMOS33 [get_ports usb_spi_mosi]
set_property IOSTANDARD LVCMOS33 [get_ports usb_spi_sclk]
set_property PACKAGE_PIN T13 [get_ports {gpio_usb_int_tri_i[0]}]
set_property PACKAGE_PIN V14 [get_ports usb_spi_sclk]
set_property PACKAGE_PIN V15 [get_ports usb_spi_mosi]
set_property PACKAGE_PIN U12 [get_ports usb_spi_miso]

set_property IOSTANDARD LVCMOS33 [get_ports gpio_usb_rst_tri_o]
set_property PACKAGE_PIN V13 [get_ports gpio_usb_rst_tri_o]
set_property PACKAGE_PIN T12 [get_ports usb_spi_ss]
set_property IOSTANDARD LVCMOS33 [get_ports usb_spi_ss]

# nds pins
set_property PACKAGE_PIN J16 [get_ports T_R0]
set_property IOSTANDARD LVCMOS33 [get_ports T_R0]
set_property PACKAGE_PIN J15 [get_ports T_R1]
set_property IOSTANDARD LVCMOS33 [get_ports T_R1]
set_property PACKAGE_PIN K16 [get_ports T_R2]
set_property IOSTANDARD LVCMOS33 [get_ports T_R2]
set_property PACKAGE_PIN K14 [get_ports T_R3]
set_property IOSTANDARD LVCMOS33 [get_ports T_R3]
set_property PACKAGE_PIN H17 [get_ports T_R4]
set_property IOSTANDARD LVCMOS33 [get_ports T_R4]
set_property PACKAGE_PIN G18 [get_ports T_R5]
set_property IOSTANDARD LVCMOS33 [get_ports T_R5]

set_property PACKAGE_PIN H16 [get_ports T_G0]
set_property IOSTANDARD LVCMOS33 [get_ports T_G0]
set_property PACKAGE_PIN H18 [get_ports T_G1]
set_property IOSTANDARD LVCMOS33 [get_ports T_G1]
set_property PACKAGE_PIN G16 [get_ports T_G2]
set_property IOSTANDARD LVCMOS33 [get_ports T_G2]
set_property PACKAGE_PIN E16 [get_ports T_G3]
set_property IOSTANDARD LVCMOS33 [get_ports T_G3]
set_property PACKAGE_PIN C11 [get_ports T_G4]
set_property IOSTANDARD LVCMOS33 [get_ports T_G4]
set_property PACKAGE_PIN C12 [get_ports T_G5]
set_property IOSTANDARD LVCMOS33 [get_ports T_G5]

set_property PACKAGE_PIN D10 [get_ports T_B0]
set_property IOSTANDARD LVCMOS33 [get_ports T_B0]
set_property PACKAGE_PIN D11 [get_ports T_B1]
set_property IOSTANDARD LVCMOS33 [get_ports T_B1]
set_property PACKAGE_PIN E15 [get_ports T_B2]
set_property IOSTANDARD LVCMOS33 [get_ports T_B2]
set_property PACKAGE_PIN H14 [get_ports T_B3]
set_property IOSTANDARD LVCMOS33 [get_ports T_B3]
set_property PACKAGE_PIN E14 [get_ports T_B4]
set_property IOSTANDARD LVCMOS33 [get_ports T_B4]
set_property PACKAGE_PIN H13 [get_ports T_B5]
set_property IOSTANDARD LVCMOS33 [get_ports T_B5]

set_property PACKAGE_PIN J14 [get_ports DCLK]
set_property IOSTANDARD LVCMOS33 [get_ports DCLK]
set_property PACKAGE_PIN F15 [get_ports GSP]
set_property IOSTANDARD LVCMOS33 [get_ports GSP]
set_property PACKAGE_PIN J13 [get_ports LS]
set_property IOSTANDARD LVCMOS33 [get_ports LS]

#hex grid pins

set_property IOSTANDARD LVCMOS25 [get_ports {hex_gridA[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_gridA[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_gridA[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_gridA[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_gridB[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_gridB[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_gridB[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_gridB[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segA[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segA[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segA[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segA[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segA[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segA[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segA[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segA[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segB[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segB[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segB[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segB[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segB[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segB[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segB[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segB[0]}]
set_property PACKAGE_PIN G6 [get_ports {hex_gridA[0]}]
set_property PACKAGE_PIN H6 [get_ports {hex_gridA[1]}]
set_property PACKAGE_PIN C3 [get_ports {hex_gridA[2]}]
set_property PACKAGE_PIN B3 [get_ports {hex_gridA[3]}]
set_property PACKAGE_PIN E6 [get_ports {hex_segA[0]}]
set_property PACKAGE_PIN B4 [get_ports {hex_segA[1]}]
set_property PACKAGE_PIN D5 [get_ports {hex_segA[2]}]
set_property PACKAGE_PIN C5 [get_ports {hex_segA[3]}]
set_property PACKAGE_PIN D7 [get_ports {hex_segA[4]}]
set_property PACKAGE_PIN D6 [get_ports {hex_segA[5]}]
set_property PACKAGE_PIN C4 [get_ports {hex_segA[6]}]
set_property PACKAGE_PIN B5 [get_ports {hex_segA[7]}]
set_property PACKAGE_PIN F3 [get_ports {hex_segB[0]}]
set_property PACKAGE_PIN G5 [get_ports {hex_segB[1]}]
set_property PACKAGE_PIN J3 [get_ports {hex_segB[2]}]
set_property PACKAGE_PIN H4 [get_ports {hex_segB[3]}]
set_property PACKAGE_PIN F4 [get_ports {hex_segB[4]}]
set_property PACKAGE_PIN H3 [get_ports {hex_segB[5]}]
set_property PACKAGE_PIN E5 [get_ports {hex_segB[6]}]
set_property PACKAGE_PIN J4 [get_ports {hex_segB[7]}]
set_property PACKAGE_PIN E4 [get_ports {hex_gridB[0]}]
set_property PACKAGE_PIN E3 [get_ports {hex_gridB[1]}]
set_property PACKAGE_PIN F5 [get_ports {hex_gridB[2]}]
set_property PACKAGE_PIN H5 [get_ports {hex_gridB[3]}]


#LED0
set_property IOSTANDARD LVCMOS33 [get_ports LED0]
set_property PACKAGE_PIN C13 [get_ports LED0]
set_property IOSTANDARD LVCMOS33 [get_ports LED1]
set_property PACKAGE_PIN C14 [get_ports LED1]
set_property IOSTANDARD LVCMOS33 [get_ports LED2]
set_property PACKAGE_PIN D14 [get_ports LED2]
set_property IOSTANDARD LVCMOS33 [get_ports LED3]
set_property PACKAGE_PIN D15 [get_ports LED3]