# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Aaro/Desktop/385/NDS_Capture_385/nds_capture/nds_capture.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_2/design_1_microblaze_0_2.xci
# IP: The module: 'design_1_microblaze_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Aaro/Desktop/385/NDS_Capture_385/nds_capture/nds_capture.gen/sources_1/bd/design_1/ip/design_1_microblaze_0_2/design_1_microblaze_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_microblaze_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Aaro/Desktop/385/NDS_Capture_385/nds_capture/nds_capture.gen/sources_1/bd/design_1/ip/design_1_microblaze_0_2/design_1_microblaze_0_2_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_microblaze_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Aaro/Desktop/385/NDS_Capture_385/nds_capture/nds_capture.gen/sources_1/bd/design_1/ip/design_1_microblaze_0_2/design_1_microblaze_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_microblaze_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Aaro/Desktop/385/NDS_Capture_385/nds_capture/nds_capture.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_2/design_1_microblaze_0_2.xci
# IP: The module: 'design_1_microblaze_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Aaro/Desktop/385/NDS_Capture_385/nds_capture/nds_capture.gen/sources_1/bd/design_1/ip/design_1_microblaze_0_2/design_1_microblaze_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_microblaze_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Aaro/Desktop/385/NDS_Capture_385/nds_capture/nds_capture.gen/sources_1/bd/design_1/ip/design_1_microblaze_0_2/design_1_microblaze_0_2_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_microblaze_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Aaro/Desktop/385/NDS_Capture_385/nds_capture/nds_capture.gen/sources_1/bd/design_1/ip/design_1_microblaze_0_2/design_1_microblaze_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_microblaze_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
